// Generated by dts-bundle-generator v9.5.1

import * as exceljs from 'exceljs';
import * as https from 'https';
import * as jsonc from 'jsonc-parser';
import * as vscode from 'vscode';

export type Cells = Record<string, string>;
export type TableKey = string | number;
export type Table = Record<TableKey, Record<string, string>>;
export type MultiTable = Record<TableKey, Record<string, string>[]>;
declare class Sheet {
	private sheet;
	constructor(sheet: exceljs.Worksheet);
	private _cells?;
	/**
	 * 存放所有的单元格，使用 `sheet.cells['A1']` 来获取单元格的值
	 */
	get cells(): Cells;
	private createCells;
	private guessTableOffset;
	/**
	 * 已某个单元格为锚点，创建一个key-value的表格。
	 * 如果不提供参数，会自动猜测一个合适的位置。
	 * @param offset 锚点位置，如 `"B2"`
	 * @param skip 标题下额外跳过的行数（可能是标题的描述）
	 */
	makeTable(offset?: string, skip?: number): Table;
	/**
	 * 已某个单元格为锚点，创建一个key-value[]的多维表格。
	 * 与 `makeTable` 不同，可以一个对象可以保存多行的数据。
	 * 如果不提供参数，会自动猜测一个合适的位置。
	 * @param offset 锚点位置，如 `"B2"`
	 * @param skip 标题下额外跳过的行数（可能是标题的描述）
	 */
	makeMultiTable(offset?: string, skip?: number): MultiTable;
}
declare namespace Table$1 {
	const path: {
		readonly toCN: {
			readonly editorunit: "\u5355\u4F4D";
			readonly soundall: "\u58F0\u97F3";
			readonly abilityall: "\u6280\u80FD";
			readonly editordecoration: "\u88C5\u9970\u7269";
			readonly editordestructible: "\u53EF\u7834\u574F\u7269";
			readonly editoritem: "\u7269\u54C1";
			readonly modifierall: "\u9B54\u6CD5\u6548\u679C";
			readonly projectileall: "\u6295\u5C04\u7269";
			readonly technologyall: "\u79D1\u6280";
		};
		readonly fromCN: {
			readonly 单位: "editorunit";
			readonly 声音: "soundall";
			readonly 技能: "abilityall";
			readonly 装饰物: "editordecoration";
			readonly 可破坏物: "editordestructible";
			readonly 物品: "editoritem";
			readonly 魔法效果: "modifierall";
			readonly 投射物: "projectileall";
			readonly 科技: "technologyall";
		};
		readonly toName: {
			readonly editorunit: "unit";
			readonly soundall: "sound";
			readonly abilityall: "ability";
			readonly editordecoration: "decoration";
			readonly editordestructible: "destructible";
			readonly editoritem: "item";
			readonly modifierall: "modifier";
			readonly projectileall: "projectile";
			readonly technologyall: "technology";
		};
		readonly fromName: {
			readonly unit: "editorunit";
			readonly sound: "soundall";
			readonly ability: "abilityall";
			readonly decoration: "editordecoration";
			readonly destructible: "editordestructible";
			readonly item: "editoritem";
			readonly modifier: "modifierall";
			readonly projectile: "projectileall";
			readonly technology: "technologyall";
		};
	};
	const name: {
		readonly toCN: {
			readonly unit: "\u5355\u4F4D";
			readonly decoration: "\u88C5\u9970\u7269";
			readonly item: "\u7269\u54C1";
			readonly ability: "\u6280\u80FD";
			readonly modifier: "\u9B54\u6CD5\u6548\u679C";
			readonly projectile: "\u6295\u5C04\u7269";
			readonly technology: "\u79D1\u6280";
			readonly destructible: "\u53EF\u7834\u574F\u7269";
			readonly sound: "\u58F0\u97F3";
		};
		readonly fromCN: {
			readonly 单位: "unit";
			readonly 装饰物: "decoration";
			readonly 物品: "item";
			readonly 技能: "ability";
			readonly 魔法效果: "modifier";
			readonly 投射物: "projectile";
			readonly 科技: "technology";
			readonly 可破坏物: "destructible";
			readonly 声音: "sound";
		};
	};
	const type: {
		readonly toLuaType: {
			readonly 100000: "number";
			readonly 100001: "boolean";
			readonly 100002: "integer";
			readonly 100003: "string";
			readonly 100004: "Point";
			readonly 100006: "Unit";
			readonly 100010: "UnitKey";
			readonly 100011: "table";
			readonly 100014: "Ability";
			readonly 100025: "Player";
			readonly 100026: "UnitGroup";
			readonly 100027: "PlayerGroup";
			readonly 100031: "Item";
			readonly 100032: "ItemKey";
			readonly 100039: "AbilityKey";
			readonly 100263: "Mover";
		};
		readonly toName: {
			readonly 100000: "\u5B9E\u6570";
			readonly 100001: "\u5E03\u5C14";
			readonly 100002: "\u6574\u6570";
			readonly 100003: "\u5B57\u7B26\u4E32";
			readonly 100004: "\u70B9";
			readonly 100006: "\u5355\u4F4D";
			readonly 100010: "\u5355\u4F4D\u7C7B\u578B";
			readonly 100011: "\u8868";
			readonly 100014: "\u6280\u80FD";
			readonly 100025: "\u73A9\u5BB6";
			readonly 100026: "\u5355\u4F4D\u7EC4";
			readonly 100027: "\u73A9\u5BB6\u7EC4";
			readonly 100031: "\u7269\u54C1";
			readonly 100032: "\u7269\u54C1\u7C7B\u578B";
			readonly 100039: "\u6280\u80FD\u7C7B\u578B";
			readonly 100263: "\u8FD0\u52A8\u5668";
		};
		readonly etype: {
			readonly 0: "\u5B57\u7B26\u4E32";
			readonly 1: "\u6574\u6570";
			readonly 2: "\u5B9E\u6570";
			readonly 4: "\u5E03\u5C14";
		};
		readonly type: {
			readonly 0: "\u5B57\u7B26\u4E32";
			readonly 1: "\u5B9E\u6570";
			readonly 2: "\u6574\u6570";
			readonly 3: "\u5E03\u5C14";
		};
	};
	type Path = keyof typeof path.toCN;
	type NameEN = keyof typeof name.toCN;
	type NameCN = keyof typeof name.fromCN;
	type TypeID = keyof typeof type.toLuaType;
}
declare namespace CSV {
	const type: {
		readonly toPath: {
			readonly unit: "editorunit";
			readonly sound: "soundall";
			readonly ability: "abilityall";
			readonly model: "editormodel";
			readonly decoration: "editordecoration";
			readonly destructible: "editordestructible";
			readonly effect: "editoreffect";
			readonly icon: "editoricon";
			readonly item: "editoritem";
			readonly physics_object: "editorphysicsobject";
			readonly physics_object_logic: "editorphysicsobjectlogic";
			readonly modifier: "modifierall";
			readonly projectile: "projectileall";
			readonly store: "storeall";
			readonly technology: "technologyall";
		};
	};
	type Type = keyof typeof type.toPath;
}
declare namespace Template {
	const path: {
		csv: {
			readonly unit: "./y3-helper/editor_table/csv/\u5355\u4F4D";
			readonly decoration: "./y3-helper/editor_table/csv/\u88C5\u9970\u7269";
			readonly item: "./y3-helper/editor_table/csv/\u7269\u54C1";
			readonly ability: "./y3-helper/editor_table/csv/\u6280\u80FD";
			readonly modifier: "./y3-helper/editor_table/csv/\u9B54\u6CD5\u6548\u679C";
			readonly projectile: "./y3-helper/editor_table/csv/\u6295\u5C04\u7269";
			readonly technology: "./y3-helper/editor_table/csv/\u79D1\u6280";
			readonly destructible: "./y3-helper/editor_table/csv/\u53EF\u7834\u574F\u7269";
			readonly sound: "./y3-helper/editor_table/csv/\u58F0\u97F3";
		};
	};
}
export type Row = Record<string, string>;
/**
 * 读取excel中的值。
 * @param rows excel中的每个对象的数据。
 * @returns 返回需要写入表中的值。
 */
export type ReaderFunc<T> = (...rows: Row[]) => NoInfer<T> | undefined;
/**
 * 对数据进行处理。
 * @param content excel中的值
 * @param source 物编中的值。如果你用def修改过，这里会传入修改后的值（用于多个项目修改同一个值）。
 */
export type AsFunc<T> = (content: string, source?: T, ...extraContents: string[]) => NoInfer<T> | undefined;
declare class AsRule<T> {
	private as?;
	constructor(as?: As<T> | undefined);
	protected value: any;
	applyAs(content: any, source?: T, ...extraContents: any[]): T | undefined;
	private _default?;
	/**
	 * 如果值为 `undefined`，则使用此默认值。
	 * @param value 默认值。
	 * @returns
	 */
	default(value?: T): this;
	private _finally?;
	/**
	 * 对数据进行最后的处理。
	 * @param callback 处理函数。
	 * @returns
	 */
	finally(callback: (value?: T) => T): this;
}
declare class ReaderRule<T> extends AsRule<T> {
	private reader;
	constructor(reader: ReaderFunc<T>, as?: As<T>);
	applyReader(rows: Row | Row[], source?: T): T | undefined;
}
export type Reader<T> = string | undefined | ReaderFunc<T> | ReaderRule<T>;
export type As<T> = AsFunc<T> | AsRule<T>;
export type EditorDataField<N extends y3.consts.Table.NameCN> = keyof y3.table.EditorData<N>;
export type EditorDataFieldType<N extends y3.consts.Table.NameCN, F extends EditorDataField<N>> = y3.table.EditorData<N>[F];
export type RuleData<N extends y3.consts.Table.NameCN> = {
	[key in EditorDataField<N>]: Reader<EditorDataFieldType<N, key>>;
};
export type RuleField<N extends y3.consts.Table.NameCN> = {
	[key in EditorDataField<N>]: key;
};
declare class Rule<N extends y3.consts.Table.NameCN> {
	tableName: N;
	path: vscode.Uri;
	sheetName?: (number | string) | undefined;
	rule: this;
	/**
	 * excel的字段读取器。
	 */
	reader: {
		/**
		 * excel的每一个对象都会调用此回调哈数，你需要返回最终写入表中的值。
		 * 返回 `undefined` 时表示不做修改（使用物编里原来的值）。
		 * @param callback 一个回调函数，需要你返回最终写入表中的值。
		 * @returns
		 */
		readonly rule: <T>(callback: ReaderFunc<T>) => ReaderRule<T>;
		/**
		 * 将值视为数字。
		 * @param title 列标题
		 * @param defaultValue 默认值，如果不传表示不做修改（使用物编里原来的值）。
		 * @returns
		 */
		readonly number: (title: string, defaultValue?: number) => ReaderRule<number>;
		/**
		 * 将值视为整数。
		 */
		readonly integer: (title: string, defaultValue?: number) => ReaderRule<number>;
		/**
		 * 将值视为布尔值。
		 * @param title 列标题
		 * @param defaultValue 默认值，如果不传表示不做修改（使用物编里原来的值）。
		 * @returns
		 */
		readonly boolean: (title: string, defaultValue?: boolean) => ReaderRule<boolean>;
		/**
		 * 将值视为数组。如果设置了 `default`，则会用默认值填充数组。
		 * @param title 列标题
		 * @param separator 分割符
		 * @param converter 数组中的每一项还会调用此函数再转换一次
		 * @returns
		 */
		readonly string: (title: string, defaultValue?: string) => ReaderRule<string>;
		/**
		 * 将值视为数组。如果设置了 `default`，则会用默认值填充数组。
		 * @param title 列标题
		 * @param separator 分割符
		 * @param converter 数组中的每一项还会调用此函数再转换一次
		 * @returns
		 */
		readonly split: <T = string>(title: string, separator: string | RegExp, converter?: (value: string) => T) => ReaderRule<T[]>;
	};
	/**
	 * 数据转换器
	 */
	as: {
		/**
		 * 将值视为数字。
		 * @param value 值
		 * @param defaultValue 默认值，如果不传表示不做修改（使用物编里原来的值）。
		 * @returns
		 */
		readonly number: (defaultValue?: number) => AsRule<number>;
		/**
		 * 将值视为整数
		 */
		readonly integer: (defaultValue?: number) => AsRule<number>;
		/**
		 * 将值视为字符串。
		 * @param value 值
		 * @param defaultValue 默认值，如果不传表示不做修改（使用物编里原来的值）。
		 * @returns
		 */
		readonly string: (defaultValue?: string) => AsRule<string>;
		/**
		 * 将值视为布尔值。
		 * @param value 值
		 * @param defaultValue 默认值，如果不传表示不做修改（使用物编里原来的值）。
		 * @returns
		 */
		readonly boolean: (defaultValue?: boolean) => AsRule<boolean>;
		/**
		 * 将值视为数组。如果设置了 `default`，则会用默认值填充数组。
		 * @param title 列标题
		 * @param separator 分割符
		 * @param converter 数组中的每一项还会调用此函数再转换一次
		 * @returns
		 */
		readonly split: <T = string>(separator: string | RegExp, converter?: (value: string) => T) => AsRule<T[]>;
	};
	private _actions;
	/**
	 * 描述字段从表里的哪些列获取数据。
	 */
	data: RuleData<N>;
	field: RuleField<N>;
	constructor(tableName: N, path: vscode.Uri, sheetName?: (number | string) | undefined);
	/**
	 * 表格中的偏移量，如 `A1`、`B2` 等。如果不提供会尝试自动查找。
	 */
	offset?: string;
	/**
	 * 要跳过多少行。如果标题下一行是描述，可以将此设置为 `1`。
	 */
	skip?: number;
	/**
	 * 对象的key在表格中的列名。如果不提供会使用第一列。
	 * 如果不存在会新建。
	 */
	key?: string;
	/**
	 * 对象从哪个模板上继承。如果不提供，或是与`key`相同则使用默认模板。
	 */
	template?: string;
	/**
	 * 是否强制创建对象。默认情况下会优先使用已有对象，保留对象已有的数据。
	 */
	overwrite?: boolean;
	/**
	 * 是否是多维表。
	 */
	multi?: boolean;
	/**
	 * 定义一个根据excel字段的生成规则
	 * @param title excel中的列标题
	 * @param field 物编中的字段
	 * @param as 数据转换器
	 */
	def<F extends EditorDataField<N>>(title: string, field: F, as?: As<EditorDataFieldType<N, F>>): void;
	/**
	 * 立即执行规则。一般来说你不需要调用，会在当前插件执行完后自动调用。
	 */
	apply(): Promise<void>;
	private getValue;
}
declare function loadFile(path: vscode.Uri | string, sheetName?: number | string): Promise<Sheet>;
declare function setBaseDir(path: vscode.Uri | string): void;
declare function rule<N extends Table$1.NameCN>(tableName: N, path: vscode.Uri | string, sheetName?: number | string): Rule<N>;
declare function init(): void;
export interface UnitData {
	/**
	 * 躲避率(%)
	 *
	 * 单位躲避其他单位普通攻击的概率
	 */
	dodge_rate: number;
	/**
	 * 普攻类型
	 */
	common_atk_type: any;
	/**
	 * 模型缩放
	 *
	 * 对当前物体模型的缩放倍数，用于调整模型大小。
	 */
	body_size: number;
	/**
	 * 法术穿透
	 *
	 * 穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_mag: number;
	/**
	 * 智力
	 *
	 * 智力
	 */
	intelligence_grow: number;
	/**
	 * 小地图头像缩放
	 *
	 * 单位在小地图上的头像的缩放
	 */
	mini_map_icon_scale: number;
	/**
	 * x轴缩放
	 */
	billboard_scale_x: number;
	/**
	 * 法术穿透
	 *
	 * 穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_mag_grow: number;
	/**
	 * 默认行为
	 *
	 * 单位默认状态下会执行的行为
	 */
	default_behaviour_type: any;
	/**
	 * 头像
	 *
	 * 单位在游戏中显示的头像
	 */
	icon: any;
	/**
	 * 初始库存
	 *
	 * 单位作为商品的初始库存
	 */
	init_stock: number;
	/**
	 * 隐藏技能
	 *
	 * 隐藏技能，放在这类技能位中的技能将不会被显示在游戏中。
	 */
	passive_ability_list: any[];
	/**
	 * 转身速度
	 *
	 * 单位的转身速度
	 */
	rotate_speed: number;
	/**
	 * 敏捷
	 *
	 * 敏捷
	 */
	agility_grow: number;
	/**
	 * 商店范围
	 */
	shop_range: number;
	/**
	 * 移动类型
	 *
	 * 影响可用的可移动通道。
	 */
	move_type: any;
	/**
	 * 物理防御力
	 *
	 * 单位的物理防御力
	 */
	defense_phy_grow: number;
	/**
	 * 法术攻击力
	 *
	 * 单位的法术攻击力
	 */
	attack_mag_grow: number;
	/**
	 * 技能资源恢复
	 *
	 * 单位的每秒技能资源恢复数值
	 */
	mp_rec_grow: number;
	/**
	 * 菲涅尔指数
	 */
	fresnel_exp: number;
	/**
	 * 转向时移动速度系数
	 *
	 * 当单位转向时，移动速度会受到一定的影响。
	 */
	speed_ratio_in_turn: number;
	/**
	 * 英雄技能
	 *
	 * 单位的英雄技能，可以通过学习升级，每次学习需要消耗一个技能点（升级时获取）。在默认UI界面中，会显示在后6个技能栏内，超出的不显示但依然生效。
	 */
	hero_ability_list: any[];
	/**
	 * 暴击伤害(%)
	 *
	 * 发生暴击时，造成的暴击伤害倍数
	 */
	critical_dmg_grow: number;
	/**
	 * 头顶名称显示方式
	 *
	 * 影响游戏内物体上方的文本显示内容。
	 */
	bar_show_name: any;
	/**
	 * 生命恢复
	 *
	 * 单位的每秒生命恢复数值
	 */
	hp_rec_grow: number;
	/**
	 * 最大生命值
	 *
	 * 单位的最大生命值
	 */
	hp_max_grow: number;
	/**
	 * 单位状态
	 *
	 * 进入游戏时，为单位附加的初始状态
	 */
	ori_bits: any;
	/**
	 * 启用圆盘阴影
	 */
	is_open_disk_shadow: boolean;
	/**
	 * 可研发科技
	 *
	 * 这些科技，可以在单位身上研发、升级。
	 */
	research_techs: any[];
	/**
	 * 开启面向移动模式
	 */
	enable_strict_facing_mode: boolean;
	/**
	 * 最大技能资源
	 *
	 * 单位的最大技能资源
	 */
	mp_max_grow: number;
	/**
	 * 主属性
	 *
	 * 英雄单位的主要属性，一般主属性的提升会对英雄有额外加成
	 */
	main_attr: any;
	/**
	 * 物理穿透
	 *
	 * 穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_phy_grow: number;
	/**
	 * 尸体消失时间
	 *
	 * 尸体消失时间
	 */
	keep_dead_body_time: number;
	/**
	 * 法术攻击力
	 *
	 * 单位的法术攻击力
	 */
	attack_mag: number;
	/**
	 * 出售列表
	 *
	 * 单位作为商店时的出售列表
	 */
	sell_list: any;
	/**
	 * 生命恢复
	 *
	 * 单位的每秒生命恢复数值
	 */
	hp_rec: number;
	/**
	 * 技能资源条颜色
	 *
	 * 该单位用来释放技能的能量的颜色
	 */
	mp_color: any;
	/**
	 * 技能资源恢复
	 *
	 * 单位的每秒技能资源恢复数值
	 */
	mp_rec: number;
	/**
	 * 求救距离
	 */
	rescue_seeker_distance: number;
	/**
	 * nil
	 */
	vision_sector_rng_grow: number;
	/**
	 * 伤害减免(%)
	 *
	 * 百分比降低受到的伤害
	 */
	dmg_reduction: number;
	/**
	 * 移动速度
	 *
	 * 单位每秒移动的距离。
	 */
	ori_speed: number;
	/**
	 * 购买开始时间
	 *
	 * 单位作为商品的可购买时间(游戏开始多久后可以购买）
	 */
	start_rft: number;
	/**
	 * 悬浮信息显示
	 *
	 * 开启后鼠标悬浮到单位身上时会显示单位名称和等级的文本框
	 */
	show_y3_extra_info: boolean;
	/**
	 * 移动速度
	 *
	 * 单位每秒移动的距离。
	 */
	ori_speed_grow: number;
	/**
	 * 特殊状态
	 *
	 * 特殊状态下会播放的动画
	 */
	special_idle_anim: string;
	/**
	 * 物理穿透(%)
	 *
	 * 百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_phy_ratio: number;
	/**
	 * 防御类型
	 *
	 * 单位的护甲类型，具体效果可在游戏规则中查看
	 */
	armor_type: any;
	/**
	 * 物理吸血(%)
	 *
	 * 造成物理伤害后可以恢复自身生命值
	 */
	vampire_phy: number;
	/**
	 * 简易普攻
	 */
	simple_common_atk: any;
	/**
	 * 物理攻击力
	 *
	 * 单位的物理攻击力
	 */
	attack_phy: number;
	/**
	 * 攻击间隔
	 */
	attack_interval_grow: number;
	/**
	 * 是否预览血条
	 */
	need_preview_billboard: boolean;
	/**
	 * 被治疗效果提升(%)
	 *
	 * 提高接受治疗时受到的治疗效果
	 */
	heal_effect_grow: number;
	/**
	 * 所有伤害加成(%)
	 *
	 * 百分比提高造成的伤害
	 */
	extra_dmg: number;
	/**
	 * 警戒范围(AI)
	 *
	 * 单位的警戒范围(AI)
	 */
	alarm_range: number;
	/**
	 * 出售获得资源
	 *
	 * 单位作为商品的出售获得资源
	 */
	sell_res_list: any[];
	/**
	 * 是否开启透视
	 */
	is_open_Xray: boolean;
	/**
	 * 敏捷
	 *
	 * 敏捷
	 */
	agility: number;
	/**
	 * 小地图头像
	 *
	 * 单位在小地图上的头像
	 */
	mini_map_icon: any;
	/**
	 * y轴缩放
	 */
	billboard_scale_y: number;
	/**
	 * 死亡
	 *
	 * 死亡状态下会播放的动画
	 */
	die_anim: string;
	/**
	 * 标签
	 *
	 * 用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
	 */
	tags: any[];
	/**
	 * 被治疗效果提升(%)
	 *
	 * 提高接受治疗时受到的治疗效果
	 */
	healing_effect_grow: number;
	/**
	 * 视野类型
	 *
	 * 单位与战争迷雾相关的一些属性
	 */
	view_type: any;
	/**
	 * 暴击伤害(%)
	 *
	 * 发生暴击时，造成的暴击伤害倍数
	 */
	critical_dmg: number;
	/**
	 * 强制显示在小地图
	 *
	 * 勾选后单位将强制显示在小地图上，无视战争阴影
	 */
	force_show_on_mini_map: boolean;
	/**
	 * 圆盘阴影大小
	 */
	disk_shadow_size: number;
	/**
	 * 物理攻击力
	 *
	 * 单位的物理攻击力
	 */
	attack_phy_grow: number;
	/**
	 * nil
	 */
	collision_radius_2: number;
	/**
	 * 死亡后是否销毁单位
	 *
	 * 死亡后是否会把单位完全销毁。（会在尸体消失时间结束后进行销毁，销毁后将无法再获取单位相关信息）
	 */
	destroy_after_die: boolean;
	/**
	 * 物理主控行走速度
	 */
	cc_walk_speed: number;
	/**
	 * 玩家颜色缩放
	 */
	role_color_scale: number;
	/**
	 * 最大技能资源
	 *
	 * 单位的最大技能资源
	 */
	mp_max: number;
	/**
	 * 法术防御力
	 *
	 * 单位的法术防御力
	 */
	defense_mag_grow: number;
	/**
	 * 物理穿透(%)
	 *
	 * 百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_phy_ratio_grow: number;
	/**
	 * 物理主控跳跃高度
	 */
	cc_jump_height: number;
	/**
	 * 名称
	 *
	 * 当前单位的名称
	 */
	name: string;
	/**
	 * 描述
	 *
	 * 单位的介绍说明，用在编辑器内和游戏内的Tips显示上
	 */
	description: string;
	/**
	 * 扇形视野夜晚夹角
	 *
	 * 单位在夜晚拥有的扇形视野夹角。
	 */
	vision_sector_angle_night: number;
	/**
	 * 是否敌友方显示不同头像
	 */
	separate_enemy_icon: boolean;
	/**
	 * 单位状态列表
	 */
	state_list: any[];
	/**
	 * 使用简易小地图头像
	 *
	 * 简易小地图头像的表现为一个小点。简易小地图头像的绘制性能消耗相比普通小地图头像更小，如果地图上会出现大量的该类型单位，建议使用简易小地图头像。
	 */
	use_simple_mini_map_icon: boolean;
	/**
	 * 启用补光效果
	 */
	use_virtual_light: boolean;
	/**
	 * 攻击范围
	 */
	attack_range_grow: number;
	/**
	 * ID
	 *
	 * 单位的唯一表示
	 */
	key: number;
	/**
	 * 最大生命值
	 *
	 * 单位的最大生命值
	 */
	hp_max: number;
	/**
	 * 物理
	 */
	physics_composite: any;
	/**
	 * 法术吸血(%)
	 *
	 * 造成法术伤害后可以恢复自身生命值
	 */
	vampire_mag: number;
	/**
	 * 法术穿透(%)
	 *
	 * 百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_mag_ratio_grow: number;
	/**
	 * nil
	 */
	is_x_offset: boolean;
	/**
	 * 出售阵营参数
	 */
	shop_camp_args: any;
	/**
	 * 菲涅尔颜色
	 */
	fresnel_color: any;
	/**
	 * 启用菲涅尔效果
	 */
	use_fresnel: boolean;
	/**
	 * 碰撞格点
	 */
	collision_points: any;
	/**
	 * nil
	 */
	width_offset: number;
	/**
	 * 物理主控跑步速度
	 */
	cc_run_speed: number;
	/**
	 * 动画状态名
	 */
	anim_state_name: string;
	/**
	 * 是否应用玩家颜色光圈
	 */
	is_apply_role_color: boolean;
	/**
	 * 单位初始状态
	 */
	state_init: any;
	/**
	 * 扇形视野白天夹角
	 *
	 * 单位在白天拥有的扇形视野夹角。
	 */
	vision_sector_angle_day: number;
	/**
	 * 攻击速度(%)
	 *
	 * 攻击速度(倍数)
	 */
	attack_speed_grow: number;
	/**
	 * 命中率(%)
	 *
	 * 单位普通攻击命中其他单位的概率
	 */
	hit_rate: number;
	/**
	 * 真实视野
	 *
	 * 单位所能侦测到隐身单位的范围
	 */
	vision_true: number;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 救援类型
	 */
	rescuer_type: any;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 真实视野
	 *
	 * 单位所能侦测到隐身单位的范围
	 */
	vision_true_grow: number;
	/**
	 * 无法移动时仍然保持目标
	 *
	 * 该字段未勾选时，在目标移动出自身的警戒范围后，且自身不能移动时，会立即开始寻找一个新的攻击目标。多用于定点守卫。
	 */
	keep_target: boolean;
	/**
	 * 所有伤害加成(%)
	 *
	 * 百分比提高造成的伤害
	 */
	extra_dmg_grow: number;
	/**
	 * 物理穿透
	 *
	 * 穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_phy: number;
	/**
	 * 命中率(%)
	 *
	 * 单位普通攻击命中其他单位的概率
	 */
	hit_rate_grow: number;
	/**
	 * 是否开启描边
	 */
	is_open_outline_pass: boolean;
	/**
	 * 被治疗效果加成(%)
	 *
	 * 提高接受治疗时受到的治疗效果
	 */
	healing_effect: number;
	/**
	 * 可移动通道
	 *
	 * 对单位移动类型的补充，决定单位究竟是在哪些通道移动。任意通道被碰撞阻挡该单位均无法通过。
	 */
	move_limitation: any;
	/**
	 * nil
	 */
	height_offset: number;
	/**
	 * 悬浮信息显示内容
	 */
	y3_extra_info_show_type: any;
	/**
	 * 单位分类
	 *
	 * 单位类型决定了这类单位的一些特性，包括其可编辑的属性和某些属性的默认值。
	 */
	type: any;
	/**
	 * 是否有技能资源条
	 *
	 * 该单位是否有可以用来释放技能的能量
	 */
	has_mp: boolean;
	/**
	 * 资源消耗
	 *
	 * 单位作为建筑时建造会消耗的资源
	 */
	build_res_cost_list: any[];
	/**
	 * 应用科技
	 *
	 * 单位的可应用科技（会受到该科技的影响）
	 */
	affect_techs: any[];
	/**
	 * 出售阵营类型
	 */
	shop_sell_type: any;
	/**
	 * 夜晚视野
	 *
	 * 单位在夜晚可以看到（驱散战争迷雾）的范围
	 */
	vision_night: number;
	/**
	 * 物品栏
	 *
	 * 单位的物品栏格数
	 */
	bar_slot_size: number;
	/**
	 * 商店
	 */
	shop_edit: any;
	/**
	 * 通用技能
	 *
	 * 单位的通用技能。在默认UI界面中，会显示在前6个技能栏内，超出的不显示但依然生效。
	 */
	common_ability_list: any[];
	/**
	 * 是否做为商店
	 *
	 * 开启后单位可以作为商店编辑出售的物品
	 */
	is_shop: boolean;
	/**
	 * 购买所需资源
	 *
	 * 单位作为商品的购买所需资源
	 */
	buy_res_list: any[];
	/**
	 * 编辑器后缀
	 *
	 * 给使用编辑器的用户看的备注，无实际作用
	 */
	suffix: string;
	/**
	 * 静态碰撞跟随面向
	 *
	 * 仅对建筑类型单位生效。勾选时，单位改变朝向时会使静态碰撞跟随旋转。
	 */
	collision_box_turning_enable: boolean;
	/**
	 * 冷却缩减(%)
	 *
	 * 单位技能进入cd时减少部分冷却时间
	 */
	cd_reduce_grow: number;
	/**
	 * 库存恢复间隔
	 *
	 * 单位作为商品的库存恢复间隔
	 */
	refresh_interval: number;
	/**
	 * 是否显示血条刻度
	 *
	 * 单位血条上是否会出现刻度线
	 */
	bar_show_scale: boolean;
	/**
	 * 攻击类型
	 *
	 * 单位的攻击类型，具体效果可在游戏规则中查看
	 */
	attack_type: any;
	/**
	 * 求救类型
	 */
	rescue_seeker_type: any;
	/**
	 * 编辑简易普攻
	 */
	jump_to_display: any;
	/**
	 * 普通攻击
	 *
	 * 单位的普通攻击，唯一，单位对目标普通攻击时释放的技能
	 */
	common_atk: any;
	/**
	 * 法术防御力
	 *
	 * 单位的法术防御力
	 */
	defense_mag: number;
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 允许移动的角度差
	 *
	 * 当单位转向时，如果转向角度小于该值，则会直接朝目标方向移动；反之会边转向，边移动。
	 */
	angle_tolerance: number;
	/**
	 * 移动类型
	 *
	 * 单位的移动类型，决定单位究竟是在地面移动还是在空中移动。
	 */
	move_channel: any;
	/**
	 * 掉落物品
	 *
	 * 单位死亡后会掉落的物品
	 */
	drop_items_tuple: any[];
	/**
	 * 取消警戒范围(AI)
	 *
	 * 单位的取消警戒范围(AI)，敌方离开取消警戒范围后会不再主动攻击敌方
	 */
	cancel_alarm_range: number;
	/**
	 * 背包栏
	 *
	 * 单位的背包栏格数
	 */
	pkg_slot_size: number;
	/**
	 * 力量
	 *
	 * 力量
	 */
	strength_grow: number;
	/**
	 * 最大平衡角度
	 */
	max_balance_angle: number;
	/**
	 * 经验
	 *
	 * 单位被敌方击杀后，敌方可获得的经验
	 */
	reward_exp: number;
	/**
	 * 救援后返回
	 */
	rescue_finish_return: boolean;
	/**
	 * 预览血量
	 */
	preview_billboard_health_value: number;
	/**
	 * 单位血条高度偏移
	 */
	billboard_height_offset: number;
	/**
	 * 离地高度
	 *
	 * 单位的离地高度
	 */
	model_height: number;
	/**
	 * 前置条件
	 *
	 * 训练、购买、建造该单位的前置条件
	 */
	precondition_list: any[];
	/**
	 * 白天视野
	 *
	 * 单位在白天可以看到（驱散战争迷雾）的范围
	 */
	vision_rng_grow: number;
	/**
	 * 攻击间隔
	 */
	attack_interval: number;
	/**
	 * 移动动画播放速率系数
	 *
	 * 单位移动时动画的播放速度
	 */
	standard_walk_rate: number;
	/**
	 * nil
	 */
	vision_sector_angle_night_grow: number;
	/**
	 * 力量
	 *
	 * 力量
	 */
	strength: number;
	/**
	 * nil
	 */
	vision_sector_angle_day_grow: number;
	/**
	 * nil
	 */
	vision_sector_night_grow: number;
	/**
	 * 白天视野
	 *
	 * 单位在白天可以看到（驱散战争迷雾）的范围
	 */
	vision_rng: number;
	/**
	 * 碰撞半径
	 *
	 * 碰撞动态半径，每50为1个标准格。
	 */
	dynamic_collision_r: number;
	/**
	 * 暴击率(%)
	 *
	 * 单位普通攻击有概率造成额外伤害
	 */
	critical_chance_grow: number;
	/**
	 * nil
	 */
	is_z_offset: boolean;
	/**
	 * 菲涅尔强度
	 */
	fresnel_emissive_color_strength: number;
	/**
	 * 物理吸血(%)
	 *
	 * 造成物理伤害后可以恢复自身生命值
	 */
	vampire_phy_grow: number;
	/**
	 * 物理防御力
	 *
	 * 单位的物理防御力
	 */
	defense_phy: number;
	/**
	 * 等级
	 *
	 * 单位的默认等级
	 */
	level: number;
	/**
	 * 血条显示模式
	 *
	 * 该单位在游戏内的血条的显示时机
	 */
	blood_show_type: any;
	/**
	 * 模型不透明度
	 */
	model_opacity: number;
	/**
	 * 基础材质变色
	 */
	base_tint_color: any;
	/**
	 * 血条样式
	 *
	 * 该单位在游戏内的血条样式
	 */
	blood_bar: any;
	/**
	 * 材质颜色叠加类型
	 */
	base_color_mod: any;
	/**
	 * 模型
	 *
	 * 当前单位所使用的的模型
	 */
	model: any;
	/**
	 * 建造时间（秒）
	 */
	build_time: number;
	/**
	 * 伤害减免(%)
	 *
	 * 百分比降低受到的伤害
	 */
	dmg_reduction_grow: number;
	/**
	 * 技能资源名称
	 *
	 * 该单位用来释放技能的能量的名称
	 */
	mp_key: string;
	/**
	 * 是否在小地图显示
	 *
	 * 单位是否会在小地图上显示出来
	 */
	is_mini_map_show: boolean;
	/**
	 * 暴击率(%)
	 *
	 * 单位普通攻击有概率造成额外伤害
	 */
	critical_chance: number;
	/**
	 * 默认状态
	 *
	 * 默认状态下会播放的动画
	 */
	idle_anim: string;
	/**
	 * 无法反击时会逃跑
	 *
	 * 当单位受到伤害且自身无法反击时，会向伤害来源的相反方向移动一段距离，仅在警戒状态下生效
	 */
	can_flee: boolean;
	/**
	 * 物理主控加速速率
	 */
	cc_move_acc_rate: number;
	/**
	 * 物理主控加速度
	 */
	cc_move_acc: number;
	/**
	 * 行走
	 *
	 * 行走状态下会播放的动作
	 */
	walk_anim: string;
	/**
	 * 冷却缩减(%)
	 *
	 * 单位技能进入cd时减少部分冷却时间
	 */
	cd_reduce: number;
	/**
	 * 求救间隔
	 */
	rescue_seeker_interval: number;
	/**
	 * 敌方小地图头像
	 */
	enemy_mini_map_icon: any;
	/**
	 * 夜晚视野
	 *
	 * 单位在夜晚可以看到（驱散战争迷雾）的范围
	 */
	vision_night_grow: number;
	/**
	 * 被治疗效果加成(%)
	 *
	 * 提高接受治疗时受到的治疗效果
	 */
	heal_effect: number;
	/**
	 * 攻击速度(%)
	 *
	 * 单位的攻击速度百分比，局内显示的实际攻速为:1/单位当前普通攻击技能冷却时间*攻击速度
	 */
	attack_speed: number;
	/**
	 * 扇形视野夜晚半径
	 *
	 * 单位在夜晚拥有的扇形视野半径。
	 */
	vision_sector_night: number;
	/**
	 * 智力
	 *
	 * 智力
	 */
	intelligence: number;
	/**
	 * 攻击范围
	 */
	attack_range: number;
	/**
	 * 扇形视野白天半径
	 *
	 * 单位在白天拥有的扇形视野半径。
	 */
	vision_sector_rng: number;
	/**
	 * 法术吸血(%)
	 *
	 * 造成法术伤害后可以恢复自身生命值
	 */
	vampire_mag_grow: number;
	/**
	 * 最大库存
	 *
	 * 单位作为商品的最大库存
	 */
	max_stock: number;
	/**
	 * 躲避率(%)
	 *
	 * 单位躲避其他单位普通攻击的概率
	 */
	dodge_rate_grow: number;
	/**
	 * 允许反击范围
	 */
	counterattack_range: number;
	/**
	 * 头顶名称字体
	 *
	 * 在单位头顶显示的文字字体
	 */
	billboard_name_font: any;
	/**
	 * 是否启用基础材质变色
	 */
	use_base_tint_color: boolean;
	/**
	 * 升级列表
	 */
	build_upgrade_list: any[];
	/**
	 * 法术穿透(%)
	 *
	 * 百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
	 */
	pene_mag_ratio: number;
}
export interface SoundData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 音量
	 */
	volume: number;
	/**
	 * 描述
	 */
	description: string;
	/**
	 * 2D声音
	 */
	sound_id: any;
	/**
	 * 最小距离
	 */
	min_dist: number;
	/**
	 * 淡出时间
	 */
	fade_out_time: number;
	/**
	 * 播放速度
	 */
	speed: number;
	/**
	 * 最大距离
	 */
	max_dist: number;
	/**
	 * 总时间
	 */
	total_time: number;
	/**
	 * 标签
	 */
	tags: any[];
	/**
	 * 图标
	 */
	icon: any;
	/**
	 * 2D声音
	 */
	sound_id_list: any[];
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 分组
	 */
	group: number;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 优先级
	 */
	priority: number;
	/**
	 * 类型
	 */
	type: number;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 淡入时间
	 */
	fade_in_time: number;
}
export interface AbilityData {
	/**
	 * 物品
	 */
	type_priority_item: number;
	/**
	 * 施法开始可以被打断
	 */
	can_ps_interrupt: boolean;
	/**
	 * 阵营
	 */
	filter_condition_camp: any;
	/**
	 * 敌人
	 */
	camp_priority_enemy: number;
	/**
	 * 可破坏物
	 */
	type_priority_destructible: number;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 近战
	 */
	is_meele: boolean;
	/**
	 * 准备特效
	 */
	sp_sfx_list: any[];
	/**
	 * 施法完成可以被打断
	 */
	can_bs_interrupt: boolean;
	/**
	 * 连续施法
	 */
	collection_continuously: boolean;
	/**
	 * 立刻施法
	 */
	is_immediate: boolean;
	/**
	 * 宽度
	 */
	arrow_width: string[];
	/**
	 * 长度
	 */
	arrow_length: string[];
	/**
	 * 消耗生命是否致死
	 */
	cost_hp_can_die: boolean;
	/**
	 * 生命值消耗
	 */
	ability_hp_cost: string[];
	/**
	 * 魔法书技能
	 */
	magicbook_list: any[];
	/**
	 * 受击特效
	 */
	hit_sfx_list: any[];
	/**
	 * 施法引导
	 */
	ability_prepare_time: number;
	/**
	 * 单位移动类型
	 */
	filter_condition_move_channel_type: any;
	/**
	 * 前摇特效
	 */
	ps_sfx_list: any[];
	/**
	 * 攻击范围预览特效
	 */
	building_attack_range_sfx: any;
	/**
	 * 可破坏物标签要求
	 */
	collection_destructible_tags: any;
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 移动会对技能产生影响
	 */
	influenced_by_move: boolean;
	/**
	 * 生命不足能否施放
	 */
	can_cast_when_hp_insufficient: boolean;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 英雄
	 */
	type_priority_hero: number;
	/**
	 * 自动拾取
	 */
	auto_pick: boolean;
	/**
	 * 消耗生命值施放
	 */
	can_cost_hp: boolean;
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 施法引导可以被打断
	 */
	can_prepare_interrupt: boolean;
	/**
	 * 玩家属性消耗
	 */
	player_props_cost: any[];
	/**
	 * 可以缓存
	 */
	can_cache: boolean;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 技能消耗
	 */
	ability_cost: string[];
	/**
	 * 采集动画
	 */
	collection_animation: string;
	/**
	 * 击中音效
	 */
	hit_sound_effect: any[];
	/**
	 * 技能释放类型
	 */
	ability_cast_type: any;
	/**
	 * 自动施法
	 */
	is_autocast: boolean;
	/**
	 * 充能时间
	 */
	ability_stack_cd: string[];
	/**
	 * 结束音效
	 */
	end_sound_effect: any[];
	/**
	 * 前置条件
	 *
	 * 训练、购买、建造该单位的前置条件
	 */
	precondition_list: any[];
	/**
	 * 生物
	 */
	type_priority_creature: number;
	/**
	 * 可以超出范围施法
	 */
	release_immediately_out_of_range: boolean;
	/**
	 * 技能伤害值
	 */
	ability_damage: string[];
	/**
	 * 角度
	 */
	sector_angle: string[];
	/**
	 * 是否转身
	 */
	need_turn_to_target: boolean;
	/**
	 * 攻击范围预览
	 */
	show_building_attack_range: boolean;
	/**
	 * 建造方式
	 */
	ability_build_subtype: any;
	/**
	 * 显示准备倒计时
	 */
	sp_count_down: boolean;
	/**
	 * 冷却时间
	 */
	cold_down_time: string[];
	/**
	 * 圆形半径
	 */
	circle_radius: string[];
	/**
	 * 是否为蓄力技能
	 */
	is_charge_ability: boolean;
	/**
	 * 建造单位
	 */
	build_list: any[];
	/**
	 * 前摇音效
	 */
	ps_sound_effect: any[];
	/**
	 * 结束特效
	 */
	end_sfx_list: any[];
	/**
	 * 后摇特效
	 */
	bs_sfx_list: any[];
	/**
	 * 循环播放动画
	 */
	collection_animation_loop: boolean;
	/**
	 * 建筑
	 */
	type_priority_building: number;
	/**
	 * 己方
	 */
	camp_priority_self: number;
	/**
	 * 建造角度
	 */
	build_rotate: number;
	/**
	 * 特殊筛选
	 */
	target_attribute: any;
	/**
	 * 攻击命令触发自动施法
	 */
	can_autocast_when_attack_target: boolean;
	/**
	 * 扇形半径
	 */
	sector_radius: string[];
	/**
	 * 物品标签要求
	 */
	filter_item_tags: any;
	/**
	 * 描述
	 */
	description: string;
	/**
	 * 单位排除标签
	 */
	forbid_unit_tags: any;
	/**
	 * 单位标签要求
	 */
	filter_unit_tags: any;
	/**
	 * 准备音效
	 */
	sp_sound_effect: any[];
	/**
	 * 施法特效
	 */
	cst_sfx_list: any[];
	/**
	 * 图标
	 */
	ability_icon: any;
	/**
	 * 施法音效
	 */
	cst_sound_effect: any[];
	/**
	 * 技能受冷却影响
	 */
	influenced_by_cd_reduce: boolean;
	/**
	 * 类型
	 */
	filter_condition_type: any;
	/**
	 * 标签
	 */
	tags: any[];
	/**
	 * 释放范围
	 */
	ability_cast_range: string[];
	/**
	 * 施法打断范围
	 */
	ability_break_cast_range: string[];
	/**
	 * 中立
	 */
	camp_priority_neutral: number;
	/**
	 * 允许学习等级
	 */
	required_level: any;
	/**
	 * 指示器类型
	 */
	sight_type: any;
	/**
	 * 施法完成
	 */
	ability_bw_point: number;
	/**
	 * 技能影响范围
	 */
	ability_damage_range: string[];
	/**
	 * 最大充能数
	 */
	ability_max_stack_count: string[];
	/**
	 * 采集获得量
	 */
	pick_count: number;
	/**
	 * 技能可以打断其他技能
	 */
	can_interrupt_others: boolean;
	/**
	 * 施法开始
	 */
	ability_cast_point: number;
	/**
	 * 施法出手
	 */
	ability_channel_time: number;
	/**
	 * 技能最大等级
	 */
	ability_max_level: number;
	/**
	 * 施法出手可以被打断
	 */
	can_cast_interrupt: boolean;
	/**
	 * 队友
	 */
	camp_priority_friend: number;
	/**
	 * 编辑技能效果
	 */
	art_resource_btn: any;
	/**
	 * 后摇音效
	 */
	bs_sound_effect: any[];
}
export interface DecorationData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 材质变色强度
	 */
	material_color_intensity: number;
	/**
	 * 高度图
	 */
	collision_height: any;
	/**
	 * 启用补光效果
	 */
	use_virtual_light: boolean;
	/**
	 * 模型
	 */
	model: any;
	/**
	 * 暂未配置55
	 */
	icon: any;
	/**
	 * 效果编辑按钮
	 */
	effect_button: any;
	/**
	 * 挂接物列表
	 */
	attach_models: any;
	/**
	 * 接收贴花
	 */
	receive_decal: boolean;
	/**
	 * 启用菲涅尔效果
	 */
	use_fresnel: boolean;
	/**
	 * 碰撞盒
	 */
	collision_box: any;
	/**
	 * 材质颜色叠加类型
	 */
	base_color_mod: any;
	/**
	 * 不透明度
	 */
	material_alpha: number;
	/**
	 * 菲涅尔指数
	 */
	fresnel_exp: number;
	/**
	 * 菲涅尔强度
	 */
	fresnel_emissive_color_strength: number;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 菲涅尔颜色
	 */
	fresnel_color: any;
	/**
	 * 是否产生阴影
	 */
	cast_shadow: boolean;
	/**
	 * nil
	 */
	enable_camera_collision: boolean;
	/**
	 * 可通行
	 */
	use_physics: boolean;
	/**
	 * 遮挡透视
	 */
	enable_occlusion_perspective: boolean;
	/**
	 * 碰撞格点
	 */
	collision_points: any;
	/**
	 * 基础材质变色
	 */
	base_tint_color: any;
	/**
	 * 基础材质变色
	 */
	material_color: any;
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 模型不透明度
	 */
	model_opacity: number;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 缩放
	 */
	scale: number;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 获得特效列表
	 */
	effect_list: any;
	/**
	 * 是否启用基础材质变色
	 */
	use_base_tint_color: boolean;
	/**
	 * 材质变化
	 */
	material_change: any;
	/**
	 * 描述
	 */
	description: string;
}
export interface DestructibleData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 小地图 - 显示
	 */
	show_on_mini_map: boolean;
	/**
	 * 资源名称
	 */
	source_desc: string;
	/**
	 * 模型缩放
	 *
	 * 对当前物体模型的缩放倍数，用于调整模型大小。
	 */
	body_size: number;
	/**
	 * 可被攻击
	 */
	is_attacked: boolean;
	/**
	 * 死亡时销毁
	 */
	destroy_on_die: boolean;
	/**
	 * 玩家属性资源
	 */
	source_player_prop: any;
	/**
	 * 启用补光效果
	 */
	use_virtual_light: boolean;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 生命值
	 */
	hp_max: number;
	/**
	 * 图标
	 */
	icon: any;
	/**
	 * 资源初始数量
	 */
	source_nums_init: number;
	/**
	 * 持续特效列表
	 */
	effect_list: any;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 接收贴花
	 */
	receive_decal: boolean;
	/**
	 * 菲涅尔强度
	 */
	fresnel_emissive_color_strength: number;
	/**
	 * 资源类型
	 */
	source_type: any;
	/**
	 * 是否可通行
	 */
	passable: boolean;
	/**
	 * nil
	 */
	dead_height_box_data: string;
	/**
	 * 资源回复间隔
	 */
	source_refresh_interval: number;
	/**
	 * 遮挡透视
	 */
	enable_occlusion_perspective: boolean;
	/**
	 * 启用菲涅尔效果
	 */
	use_fresnel: boolean;
	/**
	 * 材质颜色叠加类型
	 */
	base_color_mod: any;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 死亡特效列表
	 */
	die_effect_list: any;
	/**
	 * 描述
	 */
	description: string;
	/**
	 * 不透明度
	 */
	material_alpha: number;
	/**
	 * 菲涅尔指数
	 */
	fresnel_exp: number;
	/**
	 * 基础材质变色
	 */
	base_tint_color: any;
	/**
	 * 物品类型
	 */
	source_item: any;
	/**
	 * 小地图 - 颜色
	 */
	mini_map_color: any;
	/**
	 * 可被采集
	 */
	is_collected: boolean;
	/**
	 * 材质变色强度
	 */
	material_color_intensity: number;
	/**
	 * 基础材质变色
	 */
	material_color: any;
	/**
	 * 物品标签
	 *
	 * 用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
	 */
	tags: any[];
	/**
	 * 菲涅尔颜色
	 */
	fresnel_color: any;
	/**
	 * 可被选中
	 */
	is_selected: boolean;
	/**
	 * 默认角度
	 */
	collision_points_dead: any;
	/**
	 * 可被作为技能目标
	 */
	is_ability_target: boolean;
	/**
	 * 资源回复数量
	 */
	source_refresh_count: number;
	/**
	 * 模型
	 */
	model: any;
	/**
	 * 默认角度
	 */
	collision_points_alive: any;
	/**
	 * 资源最大数量
	 */
	source_nums_max: number;
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 模型不透明度
	 */
	model_opacity: number;
	/**
	 * 死亡销毁延迟
	 */
	destroy_delay: number;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 资源耗尽时死亡
	 */
	die_on_source_run_out: boolean;
	/**
	 * nil
	 */
	alive_height_box_data: string;
	/**
	 * 是否启用基础材质变色
	 */
	use_base_tint_color: boolean;
	/**
	 * 材质变化
	 */
	material_change: any;
	/**
	 * 默认角度
	 */
	collision_box: any;
}
export interface ItemData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 掉落后时间到期消失
	 */
	delete_on_discard: boolean;
	/**
	 * 可以遗弃
	 *
	 * 玩家是否可以将物品丢弃到地面
	 */
	discard_enable: boolean;
	/**
	 * 合成素材
	 *
	 * 合成这件物品所需要的材料，拥有所有合成原料后会自动合成该物品
	 */
	compose_list: any[];
	/**
	 * 启用补光效果
	 */
	use_virtual_light: boolean;
	/**
	 * ID
	 *
	 * 物品的ID
	 */
	key: number;
	/**
	 * 购买开始时间
	 *
	 * 游戏开始后多长时间才能购买该类物品
	 */
	start_rft: number;
	/**
	 * 前置条件
	 *
	 * 训练、购买、建造该单位的前置条件
	 */
	precondition_list: any[];
	/**
	 * 图标
	 *
	 * 物品的头像
	 */
	icon: any;
	/**
	 * 开启碰撞
	 */
	disable_overlapping: boolean;
	/**
	 * 初始库存
	 *
	 * 物品作为商品时在商店中的初始可购买数
	 */
	init_stock: number;
	/**
	 * 特效列表
	 */
	effect_list: any;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 堆叠类型
	 *
	 * 物品的堆叠或者充能逻辑。
	 */
	stack_type: any;
	/**
	 * 库存恢复间隔
	 *
	 * 当前物品作为商品时，商店库存增加的间隔时间
	 */
	refresh_interval: number;
	/**
	 * 主动技能
	 *
	 * 使用该物品的时释放的主动技能
	 */
	attached_ability: any;
	/**
	 * 启用菲涅尔效果
	 */
	use_fresnel: boolean;
	/**
	 * 消失时间
	 *
	 * 掉落在地面上的消失时间
	 */
	drop_stay_time: number;
	/**
	 * 菲涅尔强度
	 */
	fresnel_emissive_color_strength: number;
	/**
	 * 被动技能
	 */
	attached_passive_abilities: any[];
	/**
	 * 描述
	 *
	 * 物品的描述和介绍
	 */
	description: string;
	/**
	 * 菲涅尔颜色
	 */
	fresnel_color: any;
	/**
	 * 持有者死亡时掉落
	 *
	 * 物品是否会在携带者死亡时掉落地面
	 */
	discard_when_dead: boolean;
	/**
	 * 不透明度
	 */
	material_alpha: number;
	/**
	 * 材质变色强度
	 */
	material_color_intensity: number;
	/**
	 * 自动使用
	 *
	 * 勾选后获得该物品时会自动使用该物品，如果不满足该物品的主动技能消耗条件则无法拾取
	 */
	auto_use: boolean;
	/**
	 * 名称显示方式
	 */
	item_billboard_type: any;
	/**
	 * 菲涅尔指数
	 */
	fresnel_exp: number;
	/**
	 * 模型
	 *
	 * 物品掉落在地面的模型
	 */
	model: any;
	/**
	 * 等级
	 *
	 * 物品的等级
	 */
	level: number;
	/**
	 * 基础材质变色
	 */
	base_tint_color: any;
	/**
	 * CD组
	 *
	 * 该物品所在的CD组，物品使用时会使单位持有的相同CD组内所有物品进入使用物品的主动技能冷却
	 */
	cd_type: string;
	/**
	 * 材质颜色叠加类型
	 */
	base_color_mod: any;
	/**
	 * 生命值
	 *
	 * 物品的生命值，生命值归零则会被销毁
	 */
	hp_max: number;
	/**
	 * 使用消耗次数
	 *
	 * 物品是堆叠类型时，每次使用该物品消耗的堆叠层数
	 */
	use_consume: number;
	/**
	 * 最大充能数
	 *
	 * 物品可以设置的最大充能层数
	 */
	maximum_charging: number;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 出售获得资源
	 *
	 * 出售到商店时获得的资源
	 */
	sell_res_list: any[];
	/**
	 * 购买所需资源
	 *
	 * 从商店里购买这件物品所需要的资源
	 */
	buy_res_list: any[];
	/**
	 * 可以被抵押
	 *
	 * 是否可以将该物品出售到商店
	 */
	sale_enable: boolean;
	/**
	 * 物品标签
	 *
	 * 用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
	 */
	tags: any[];
	/**
	 * 默认堆叠数
	 */
	cur_stack: number;
	/**
	 * 材质变化颜色
	 */
	material_color: any;
	/**
	 * 最大堆叠
	 *
	 * 物品可以叠加的最大堆叠层数。重复获得物品时，在不大于该值的情况下物品会自动堆叠。
	 */
	maximum_stacking: number;
	/**
	 * 模型不透明度
	 */
	model_opacity: number;
	/**
	 * 最大库存
	 *
	 * 物品作为商品时在商店中的最大可购买数
	 */
	max_stock: number;
	/**
	 * 编辑器后缀
	 *
	 * 在编辑器下显示在名字后面的后缀，在游戏内不显示
	 */
	suffix: string;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 默认充能数
	 */
	cur_charge: number;
	/**
	 * 是否启用基础材质变色
	 */
	use_base_tint_color: boolean;
	/**
	 * 材质变化
	 */
	material_change: any;
	/**
	 * 尺寸
	 *
	 * 物品模型的缩放比例
	 */
	body_size: number;
}
export interface ModifierData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 是否影响自己
	 */
	is_influence_self: boolean;
	/**
	 * 材质变色强度
	 */
	material_color_intensity: number;
	/**
	 * 最大持续时间
	 */
	get_effect_list: any;
	/**
	 * 最大持续时间
	 */
	attach_model_list: any;
	/**
	 * 同源覆盖
	 */
	same_origin_cover: boolean;
	/**
	 * 不影响单位标签
	 */
	ign_inf_unit_tag: any[];
	/**
	 * 护盾类型
	 */
	shield_type: any;
	/**
	 * 目标允许
	 */
	target_allow: any;
	/**
	 * 图标
	 */
	modifier_icon: any;
	/**
	 * 最大持续时间
	 */
	lose_effect_list: any;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 效果影响
	 */
	modifier_effect: any;
	/**
	 * 覆盖护盾变化
	 */
	shield_change_of_cover: any;
	/**
	 * 影响单位标签
	 */
	inf_unit_tag: any[];
	/**
	 * 描述
	 */
	description: string;
	/**
	 * 覆盖类型
	 */
	modifier_cover_type: any;
	/**
	 * 覆盖层数变化
	 */
	layer_change_of_cover: any;
	/**
	 * 标签
	 */
	tags: any[];
	/**
	 * 不透明度
	 */
	material_alpha: number;
	/**
	 * 基础材质变色
	 */
	material_color: any;
	/**
	 * 层数上限
	 */
	layer_max: number;
	/**
	 * 效果类别
	 */
	modifier_type: any;
	/**
	 * 循环周期
	 */
	cycle_time: number;
	/**
	 * 不影响单位类型
	 */
	ign_inf_unit_type: any;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 是否死亡时消失
	 */
	disappear_when_dead: boolean;
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 光环效果
	 */
	halo_effect: any;
	/**
	 * 影响范围
	 */
	influence_rng: number;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 覆盖时间变化
	 */
	time_change_of_cover: any;
	/**
	 * 显示图标
	 */
	show_on_ui: boolean;
	/**
	 * 材质变化
	 */
	material_change: any;
	/**
	 * 护盾值
	 */
	shield_value: number;
}
export interface ProjectileData {
	/**
	 * 字符串ID
	 */
	uid: string;
	/**
	 * 描述
	 */
	description: string;
	/**
	 * 敌方特效
	 */
	effect_foes: any;
	/**
	 * 可移动通道
	 *
	 * 对单位移动类型的补充，决定单位究竟是在哪些通道移动。任意通道被碰撞阻挡该单位均无法通过。
	 */
	move_limitation: any;
	/**
	 * ID
	 */
	key: number;
	/**
	 * 标签
	 */
	tags: any[];
	/**
	 * 移动类型
	 *
	 * 单位的移动类型，决定单位究竟是在地面移动还是在空中移动。
	 */
	move_channel: any;
	/**
	 * 图标
	 */
	icon: any;
	/**
	 * 是否立即移除表现
	 */
	effect_destroy_way_is_immediately: boolean;
	/**
	 * 声音事件列表
	 */
	sound_event_list: any[];
	/**
	 * 是否循环播放
	 */
	sfx_loop: boolean;
	/**
	 * 最大持续时间
	 */
	max_duration: number;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * 特效配置
	 */
	effect_friend: any;
	/**
	 * 编辑器后缀
	 */
	suffix: string;
	/**
	 * 区分敌我特效显示
	 */
	async_effect: boolean;
}
export interface TechData {
	/**
	 * UID
	 */
	uid: string;
	/**
	 * 影响单位标签
	 */
	affect_tags: any[];
	/**
	 * 描述信息
	 */
	description: string;
	/**
	 * 编辑器后缀
	 *
	 * 在编辑器下显示在名字后面的后缀，在游戏内不显示
	 */
	suffix: string;
	/**
	 * 玩家自定义
	 */
	kv: any;
	/**
	 * 影响全部单位
	 */
	affect_all: boolean;
	/**
	 * 名称
	 */
	name: string;
	/**
	 * ID
	 *
	 * 单位的唯一表示
	 */
	key: number;
	/**
	 * 应用科技
	 */
	cells: any;
	/**
	 * 标签
	 */
	tags: any[];
	/**
	 * 最大等级
	 */
	max_lv: number;
}
export type KV = Record<string, string | number | boolean>;
export interface CommonPatch {
	/**
	 * 存放自定义的键值对。新增值只能为字符串、数字或布尔值。
	 */
	kv: KV;
}
export type Data<T> = Omit<T, keyof CommonPatch> & CommonPatch;
export type EditorData<N extends Table$1.NameCN> = N extends "\u5355\u4F4D" ? Data<UnitData> : N extends "\u58F0\u97F3" ? Data<SoundData> : N extends "\u6280\u80FD" ? Data<AbilityData> : N extends "\u88C5\u9970\u7269" ? Data<DecorationData> : N extends "\u53EF\u7834\u574F\u7269" ? Data<DestructibleData> : N extends "\u7269\u54C1" ? Data<ItemData> : N extends "\u9B54\u6CD5\u6548\u679C" ? Data<ModifierData> : N extends "\u6295\u5C04\u7269" ? Data<ProjectileData> : N extends "\u79D1\u6280" ? Data<TechData> : never;
export type ItemShape = string | boolean | number | null | TupleShape | MapShape | ArrayShape;
export type ArrayShape = ItemShape[];
export type TupleShape = {
	__tuple__: true;
	items: ItemShape[];
};
export type MapShape = {
	[key: string]: any;
};
declare class FieldInfo {
	tableName: Table$1.NameCN;
	field: string;
	desc?: string;
	tips?: string;
	type?: string;
	constructor(tableName: Table$1.NameCN, field: string);
}
declare function ready(): Promise<void>;
declare class EditorObject<N extends Table$1.NameCN> {
	tableName: N;
	key: number;
	private _json?;
	private _name?;
	text?: string;
	uri?: vscode.Uri;
	constructor(tableName: N, key: number);
	toString(): string;
	/**
	 * 获取对象的json数据语法树
	 */
	get json(): y3.json.Json | undefined;
	/**
	 * 获取对象的物编数据
	 */
	private _data?;
	get data(): EditorData<N>;
	private get;
	set(key: string, value: ItemShape, convertType?: boolean): boolean;
	private rawGet;
	private rawSet;
	/**
	 * 获取对象的名称
	 */
	get name(): string;
	private updateFile;
	getFieldInfo(field: string): y3.table.FieldInfo | undefined;
	private _fieldList?;
	listFields(): string[];
	private serialize;
	private deserialize;
}
export interface CreateOptions<N extends Table$1.NameCN> {
	/**
	 * 新对象的名称，如果不填则使用默认名称
	 */
	name?: string;
	/**
	 * 新对象的key，如果不填则自动生成
	 */
	key?: number;
	/**
	 * 从哪个对象复制，如果不填则从模板复制为空对象
	 */
	copyFrom?: number | EditorObject<N>;
	/**
	 * 如果目标key已存在，是否覆盖
	 */
	overwrite?: boolean;
}
declare class EditorTable<N extends Table$1.NameCN> extends vscode.Disposable {
	name: N;
	uri: vscode.Uri;
	nameEN: {
		readonly 单位: "unit";
		readonly 装饰物: "decoration";
		readonly 物品: "item";
		readonly 技能: "ability";
		readonly 魔法效果: "modifier";
		readonly 投射物: "projectile";
		readonly 科技: "technology";
		readonly 可破坏物: "destructible";
		readonly 声音: "sound";
	}[N];
	private _objectCache;
	private watcher?;
	constructor(name: N);
	toString(): string;
	/**
	 * 获取具体的对象
	 * @param key 对象的key（一串数字）
	 * @returns 对象
	 */
	get(key: number): Promise<EditorObject<N> | undefined>;
	fetch(key: number): EditorObject<N> | undefined;
	private _listCache?;
	/**
	 * 获取这个类型下的所有对象的key
	 * @returns 这个类型下的所有对象的key
	 */
	getList(): Promise<number[]>;
	fetchList(): number[] | undefined;
	/**
	 * 删除一个对象
	 * @param key 对象的key
	 */
	delete(key: number): Promise<void>;
	/**
	 * 检查一个key是否可以使用
	 * @param key 要检查的key
	 * @param overwirte 是否允许覆盖已有的key，默认不允许
	 * @returns
	 */
	canUseKey(key: number, overwirte?: boolean): Promise<boolean>;
	/**
	 * 生成一个可用的新key
	 * @returns
	 */
	makeNewKey(copyKey?: number): Promise<number>;
	/**
	 * 创建一个对象
	 * @param options 创建的参数
	 * @returns
	 */
	create(options?: CreateOptions<N>): Promise<EditorObject<N> | undefined>;
	/**
	 * 获取对象在硬盘中的文件路径
	 * @param key 对象的key
	 * @returns 对象的路径
	 */
	getUri(key: number): vscode.Uri;
	private _fieldInfoCache;
	getFieldInfo(field: string): FieldInfo | undefined;
	listFields(): string[];
	private _listActions;
	private resortList;
	private notifyChange;
	private changeTable;
	private _onDidChange;
	private initWatcher;
	onDidChange(callback: () => void): vscode.Disposable;
}
declare function openTable<N extends Table$1.NameCN>(tableName: N): EditorTable<N>;
declare function getFileKey(fileName: string): number | undefined;
declare function getObject(uri: vscode.Uri | string): Promise<EditorObject<Table$1.NameCN> | undefined>;
declare function getAllObjects(): Promise<y3.table.EditorObject<"\u5355\u4F4D" | "\u58F0\u97F3" | "\u6280\u80FD" | "\u88C5\u9970\u7269" | "\u53EF\u7834\u574F\u7269" | "\u7269\u54C1" | "\u9B54\u6CD5\u6548\u679C" | "\u6295\u5C04\u7269" | "\u79D1\u6280">[]>;
declare function init$1(): void;
declare function init$2(): void;
declare function ready$1(): Promise<void>;
declare function get(key: string | number): string | undefined;
declare function set(key: string | number, value: string): Promise<void>;
declare function keyOf(value: string | number, preferNumber?: boolean): string | number;
export declare function download(options: string | URL | https.RequestOptions): Promise<Buffer>;
export declare let log: vscode.LogOutputChannel;
declare class File {
	private _data;
	write(data: Uint8Array): this;
	get buffer(): Buffer;
	get string(): string;
}
declare function readFile(uri: vscode.Uri | string, relativePath?: string): Promise<File | undefined>;
declare function writeFile(uri: vscode.Uri | string, relativePath: string | undefined, data: string): Promise<boolean>;
declare function writeFile(uri: vscode.Uri | string, data: string): Promise<boolean>;
export interface DeleteOptions {
	/**
	 * 递归删除文件夹
	 */
	recursive?: boolean;
	/**
	 * 尝试移动到回收站
	 */
	useTrash?: boolean;
}
declare function removeFile(uri: vscode.Uri | string, options?: DeleteOptions): Promise<boolean>;
declare function removeFile(uri: vscode.Uri | string, relativePath?: string, options?: DeleteOptions): Promise<boolean>;
declare function dir(uri: vscode.Uri | string, relativePath?: string): Promise<[
	string,
	vscode.FileType
][]>;
declare function scan(uri: vscode.Uri | string, relativePath?: string): Promise<[
	string,
	vscode.FileType
][]>;
declare function stat(uri: vscode.Uri | string, relativePath?: string): Promise<vscode.FileStat | undefined>;
declare function isFile(uri: vscode.Uri | string, relativePath?: string): Promise<boolean>;
declare function isDirectory(uri: vscode.Uri | string, relativePath?: string): Promise<boolean>;
declare function isExists(uri: vscode.Uri | string, relativePath?: string): Promise<boolean>;
export interface CopyOptions {
	overwrite?: boolean;
	recursive?: boolean;
	nameMap?: string;
	pattern?: RegExp;
}
declare function copy(source: vscode.Uri | string, target: vscode.Uri | string, options?: CopyOptions): Promise<boolean>;
declare function isRelativePath(path: string): boolean;
declare function isAbsolutePath(path: string): boolean;
export type Item = string | boolean | number | null | JObject | JArray;
export type JArray = Item[];
export type JObject = {
	[key: string]: Item;
};
declare class Json {
	private _text;
	constructor(text: string);
	get text(): string;
	private _data?;
	get data(): JObject | undefined;
	private _tree?;
	get tree(): jsonc.Node | undefined;
	get(key: string): Item | undefined;
	private _patch?;
	set(key: string, value: any): boolean;
	private applyPatch;
}
declare function parse(text: string): any;
declare const encodeOptions: {
	readonly newline: "\n";
	readonly indent: "    ";
	readonly depth: 0;
};
declare function encode(jsObject: any, options?: Partial<typeof encodeOptions>): string;
export type EditorVersion = "1.0" | "2.0" | "unknown";
declare class Env {
	private envChangeEmitter;
	onDidChange: vscode.Event<void>;
	private searchEditorUriByReg;
	private isValidEditorPath;
	private searchEditorUri;
	private getEditorVersion;
	private searchMapPathInProject;
	private searchMapFolderBySelectedUri;
	private searchProjectPath;
	private getEditorExeUri;
	editorVersion: EditorVersion;
	editorUri?: vscode.Uri;
	editorExeUri?: vscode.Uri;
	mapUri?: vscode.Uri;
	scriptUri?: vscode.Uri;
	y3Uri?: vscode.Uri;
	pluginUri?: vscode.Uri;
	projectUri?: vscode.Uri;
	editorTableUri?: vscode.Uri;
	csvTableUri?: vscode.Uri;
	excelUri?: vscode.Uri;
	ruleUri?: vscode.Uri;
	private _tableTypeToCSVfolderPath;
	get tableTypeToCSVfolderPath(): {
		[key: string]: string;
	};
	private _editorTablePath;
	get editorTablePath(): string;
	/**
	 * 从插件配置中更新物编数据类型对应的CSV文件保存地址
	 */
	private initTableTypeToCSVfolderPath;
	private _timer?;
	private fireOnDidReload;
	updateEditor(askUser?: boolean): Promise<void>;
	editorReady(askUser?: boolean): Promise<void>;
	updateMap(search: boolean, askUser: boolean): Promise<void>;
	mapReady(askUser?: boolean): Promise<void>;
	reload(): void;
}
export declare const env: Env;
declare function runAllPlugins(funcName: string): Promise<void>;
declare function onceDidRun(callback: (data: {
	funcName: string;
	result: any;
}) => void | Promise<void>): void;
declare function init$3(): Promise<void>;
export declare let helper: vscode.ExtensionContext;
/**
 * 拼接路径为 Uri
 * @returns
 */
export declare function uri(base: vscode.Uri | string, ...paths: string[]): vscode.Uri;
/**
 * 获取《Y3开发助手》插件的相对路径
 * @returns
 */
export declare function extensionPath(...paths: string[]): vscode.Uri;
export declare function setContext(ctx: vscode.ExtensionContext): void;
/**
 * 打印内容，也会打印到日志窗口中
 * @param args 要打印的内容
 */
export declare function print(...args: any[]): void;
/**
 * 在VSCode中打开文件
 * @param uri 文件路径
 */
export declare function open(uri: vscode.Uri | string): void;
/**
 * 在Windows中打开文件
 * @param uri 文件路径
 */
export declare function openInExplorer(uri: vscode.Uri | string): void;
export declare function sleep(ms: number): Promise<void>;
export declare function assert(exp: any, msg?: string): void;

declare namespace lua {
	export { encode };
}
declare namespace plugin {
	export { init$3 as init, onceDidRun, runAllPlugins };
}
declare namespace excel {
	export { init, loadFile, rule, setBaseDir };
}
declare namespace table {
	export { EditorData, EditorObject, EditorTable, FieldInfo, getAllObjects, getFileKey, getObject, init$1 as init, openTable, ready };
}
declare namespace language {
	export { get, init$2 as init, keyOf, ready$1 as ready, set };
}
declare namespace fs {
	export { copy, dir, isAbsolutePath, isDirectory, isExists, isFile, isRelativePath, readFile, removeFile, scan, stat, writeFile };
}
declare namespace json {
	export { Item, JArray, JObject, Json, parse };
}
declare namespace consts {
	export { CSV, Table$1 as Table, Template };
}
declare namespace y3 {
	export { consts, excel, fs, json, language, lua, plugin, table };
}

export {
	consts,
	excel,
	fs,
	json,
	language,
	lua,
	plugin,
	table,
};

export {};
