export interface MapUnit { }
export interface MapSound { }
export interface MapAbility { }
export interface MapDecoration { }
export interface MapDestructible { }
export interface MapItem { }
export interface MapModifier { }
export interface MapProjectile { }
export interface MapTech { }
